# Generated by Django 4.0.4 on 2022-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_index',
            field=models.CharField(default='hello', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
