# Generated by Django 4.0.4 on 2022-05-03 15:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile_cart_alter_profile_city_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
