# Generated by Django 4.0.4 on 2022-05-03 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 39, 21, 743965, tzinfo=utc)),
        ),
    ]
